scheme: Mist
menu:
  home: / || home
  #tags: /tags/ || tags
  categories: /categories/ || th
  archives: /archives/ || archive
  about: /about/ || user
  #Note: /note/ || archive
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat

pjax:
  enable: true
aplayer:
  enable: true

google_site_verification: kQXSFnxSO1A2GvnkSAIst9BC610WXigYT0YSgZgF9O8
google_analytics: UA-120228469-1

disqus:
  enable: true
  shortname: tsukiblog
  count: true
  lazyload: false

social:
  GitHub: https://github.com/tsuki || github
  #E-Mail: mailto:yourname@gmail.com || envelope
  #Google: https://plus.google.com/yourname || google
  #Twitter: https://twitter.com/yourname || twitter
  #FB Page: https://www.facebook.com/yourname || facebook
  #VK Group: https://vk.com/yourname || vk
  #StackOverflow: https://stackoverflow.com/yourname || stack-overflow
  #YouTube: https://youtube.com/yourname || youtube
  #Instagram: https://instagram.com/yourname || instagram
  #Skype: skype:yourname?call|chat || skype

links:
  PoiScript: https://blog.poi.cat
  夢路: https://blog.ikke.moe/

auto_excerpt:
  enable: true
  length: 150

#sidebar:
#  display: always

fancybox: true
custom_file_path:
  # Default paths: layout/_custom/*
  #head: source/_data/head.swig
  header: source/_data/header.swig
  sidebar: source/_data/sidebar.swig

  # Default path: source/css/_variables/custom.styl
  #variables: source/_data/variables.styl
  # Default path: source/css/_mixins/custom.styl
  #mixins: source/_data/mixins.styl
  # Default path: source/css/_custom/custom.styl
  #styles: source/_data/styles.styl
